### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#1]
# Contributing Guidelines

1. Review the [teaching philosophy](https://github.com/LDSSA/wiki/wiki/Teaching-Philosophy) (if needed) and related guidelines (if exist)
2. Review structure of the Academy (e.g., bootcamp duration, number of specializations)
2. Define who can contribute to curriculum development (the 🌏?)
3. Define timelines to (1) propose and (2) release curriculum changes
    1. Bootcamp
    2. Specializations (including the Specialization Lead)
5. Define the approval process for curriculum changes
    1. Triaging proposals (upvotes?)
    2. Release changes.

Finally, add a [contributing file](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) to the repository.

**Comment by dominguezmaria** [comment]
After offline discussion with @jtascensao , I'm suggesting the following deadlines for the curriculum development:

**By mid March**
- The subject of each SLU in the bootcamp
- The subject of each specialisation
- The order in which the specialisations will happen

This way we can:
- Start assigning instructors to SLUs
- Start recruiting specialisation leads, already knowing when the specialisation will happen

**By the end of March**
- All the curriculum should be defined, without further major changes

This way we can:
- Close the assignment of instructors to SLUs
- Start the QA process to know exactly how much can we re-use from last year's SLUs
- Instructors can start working on the SLUs
- Recruit specialisation leads with all the info that we need

All thoughts on this are welcome!

**Comment by PedroGFonseca** [comment]
Re teaching philosophy: working on it, has been delayed by me
