### ISSUE TITLE
Companion Notation Guide

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#10]
# Notation Guide

Create a *Notation Guide* for the Academy.

## Context

We never define quite clearly:

- The setting of a machine learning problem
- Standard notation and definitions for the course.

I believe this is important for clarity, precision, and also, the way I see it, simplicity.

## Detailed Description

We would need to create what I'm calling the **Companion Notation Guide**.

It could be included in the bootcamp repository, as a cheatsheet of sorts. As it stands, I wouldn't push for a dedicated SLU on problem definition, notation, and definitions, but it's not unthinkable.

Feedback is most welcome on how to make this work.

The way I see it, this wouldn't require changes. It could, however, as:

- Units can be simplified, as notation gets sorted *a priori*
- We can have an SLU dedicated to introducing the problem, notation, and definitions (see above).

**Comment by PedroGFonseca** [comment]
Intuitively I agree, but can you give a couple of examples?

**Comment by PedroGFonseca** [comment]
(le ping)

**Comment by jtascensao** [comment]
Not unlike [this one](https://github.com/LDSSA/batch2-blu10-instructors/blob/master/Learning%20Notebooks/BLU10%20-%20Learning%20Notebook%20-%20Part%201%20of%203%20-%20Framework.ipynb), but more generic.
