### ISSUE TITLE
Bootcamp materials upgrade from batch 2

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/curriculum-development#13]
# Bootcamp materials upgrade from batch 2

## Context

At the end of Batch 2 there were a bunch of small upgrades that needed doing. Even though there won't be a direct match between the structure of batch 2 and 3, I thought it would be useful enough to provide the upgrade on the bootcamp materials, so that we are iterating on a better version.

## Detailed Description

This contains a large number of small changes all across the bootcamp materials. To facilitate things, I've created the [Upgrade Proposal repo](https://github.com/LDSSA/batch-2-bootcamp-upgrade-proposal) (which is private as it contains solutions). 

The main type of changes are:
- Simplifying questions 
- Simplifying / refactoring explanations 
- Adding asserts to all questions 
- Removing ambiguity in questions 
- Making questions not depend on previous results 
- Hiding "operational" code to help students focus on the important part (hiding stuff in utils, etc) 

In each SLU I've included 
- the changed files, 
- HTML files with the diff, created with [NbDime](https://github.com/jupyter/nbdime). 
    - They look a bit [like this](https://nbdime.readthedocs.io/en/latest/cli.hml#nbdiff-web), and can only be rendered well in the browser (GitHub doesn't quite cut it yet). 

## Possible Implementation
When the new curriculum gets assigned, it is only natural that we start with the previous year materials. I recommend this one be used to complement the [Bootcamp 2 - Instructors](https://github.com/LDSSA/batch2-bootcamp-instructors) repo. 

## [Upgrade Proposal repo](https://github.com/LDSSA/batch-2-bootcamp-upgrade-proposal) 
(just the link again for reference)

**Comment by jtascensao** [comment]
Discussed offline: the plan is for SLU owners to update their SLUs based on this.
