### ISSUE TITLE
In the curriculum, apply is mentioned before being explained 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/curriculum-development#16]
## Context

In the [new curriculum, SLU04](https://github.com/LDSSA/curriculum-development/blob/master/curriculum/01-bootcamp.md#slu04) we tell students not to use `pd.apply` in outlier detection, but they don't know what that means yet  

## Detailed Description

> Provide a detailed description of the change or addition.

> What Specialization, BLU, or SLU is it a part of (if any)?
New SLU04 

## Possible Implementation

> Suggest an idea for implementing the changes.
Suggested: not mention it 

> This does not need to be a fully-fledged plan but at least provide a concrete starting point.

**Comment by jtascensao** [comment]
Great point. Although it was not a particularly bright thing to do, the note is there *for the teacher* and not the students (i.e., to be included as a note in the SLU). 

The current material uses `.apply()`, so it needs to be re-done.

Will fix it by making it clear that this is a note for the teacher.
