### ISSUE TITLE
Very heavy content in most of the SLUs

### ISSUE THREAD

**Issue by dominguezmaria** [LDSSA/curriculum-development#17]
## Context

I'm opening this issue because I think that for most of the SLUs, the curriculum, as defined in [this PR](https://github.com/LDSSA/curriculum-development/pull/12), has too much content for the current SLU format.

I propose that we either:
* review the curriculum and cut off some parts;
* introduce a small change in the SLU format, to be able to teach everything included in the curriculum, without overwhelming the students. 

## Detailed Description

This is the comment left in the PR, but since the PR was already closed, I moved it into this issue.

---------

@jtascensao sorry to be late for the party, but just had to opportunity to review this now 😞 

Overall, I'm a bit concerned about the amount of content that we're including in each SLU, taking in consideration that we only have 15 minutes for the presentation.
I know that we're teaching based on intuition instead of using complicated mathematical explanations, but still, there are some cases where we're trying to explain in 5 minutes what I remember learning 50x more slowly in college... (Not kidding, I have proof!)

The topics that are worrying me **a lot** are:
* SLU04: skew, kurtosis, pdf and cdf
* SLU08: gradient descent (even if just intro)
* SLU09: different types of regularisation for linear models
* SLU12: kernel trick and kernels

(Then there are others that are worrying me a bit...)

Basically, the dilemma is that the curriculum (as it is) is very high quality and complete. So we don't feel like leaving anything behind. But then, the pace we're proposing here is insane and I think that most of the SLUs have too much content to be presented (and properly learned by the students) in 15 minutes. We're simply trying to "meter o Rossio na Rua da Betesga".

So, my suggestion is that we do one of these two:
a) cut down some of the content (and we should think carefully about what should be excluded)
b) still include everything but change the SLU format a bit 😱

<a href="https://imgflip.com/i/2zano1"><img src="https://i.imgflip.com/2zano1.jpg" title="made at imgflip.com"/></a>

I know this is disruptive... But bare with me a bit 😅 So, we could do the following:
* An SLU could have a new section called _Homework_ / _More on this topic_ / _Advanced but important stuff_ / _etc_, with the topics that we think are important but a bit too much to be included on the 15 min presentation + 45 min exercises. 
* This section would have some more content, that would be presented in BLU style, i.e, explained in detail in a notebook and not in the presentation, and exercises. The student should only focus on this content and exercises when the first part of the SLU is finished, which will (very likely) only happen after the bootcamp, **at home**.
* These exercises must be submitted through the grader for the SLU to be complete, i.e, they are **not optional**. They are just homework.
* The extra content/exercises **should not exist in all the SLUs**. In fact, we should try to avoid it: they should only be there when we feel that the content is too important not to be transmitted to the students, but we just don't have enough time to do it in 1 hour.

I think that the most important thing that we learned from the bootcamp last year is that the students felt it was too much, and that most of the times they were just too tired to absorb new concepts. And this curriculum (despite brilliant), feels even denser than last year's...

Now, 🔫🔫🔫 😛

**Comment by dominguezmaria** [comment]
@PedroGFonseca can you give us your precious insight on this one? 😇

**Comment by PedroGFonseca** [comment]
I agree with the problem. 

Regarding the solution I'm a bit more divided. There are a number of topics which, all together, are starting to feel like they should go in a specialisation. That would make the Academy specialisations: 
```
S1: Bootcamp
S2: Data Science - beyond the basics <--- where all this would go 
S3: Data Wrangling 
S4: ...  
```

The reasoning here would be that they will already be struggling to complete the SLUs in month 1, so adding more homework may be too much. The flip side of that is that adding another specialisation may be just logistically impossible at this point. Thoughts?

**Comment by dominguezmaria** [comment]
> I agree with the problem.
> 
> Regarding the solution I'm a bit more divided. There are a number of topics which, all together, are starting to feel like they should go in a specialisation. That would make the Academy specialisations:
> 
> ```
> S1: Bootcamp
> S2: Data Science - beyond the basics <--- where all this would go 
> S3: Data Wrangling 
> S4: ...  
> ```
> The reasoning here would be that they will already be struggling to complete the SLUs in month 1, so adding more homework may be too much. The flip side of that is that adding another specialisation may be just logistically impossible at this point. Thoughts?

I'm afraid that adding a new specialisation might be a logistics nightmare at this point 😞
What if we go with the homework approach but make the deadline for these exercises more towards the end of the course?
Of course that that revives the problem of them needing to go back to SLUs way after that's desirable...

**Comment by gaborsomogyi** [comment]
I think we should consider a deeper question: do we want to make sure everyone who starts the course finishes it as well, or are we okay with a 'planned' attrition, where we knowingly throw the people into too deep water, and expect that not all of them would swim, but those who do get better off.

Since we're already making a harder entry test, I would keep the currently proposed curriculum, and go even heavier than last year on warning the students that this is not going to be an easy ride, but it will be worth it and both the instructors and the community (which is going pretty well in the prep course) are there to support in case of any questions.

**Comment by jtascensao** [comment]
To @gaborsomogyi's point, this year we **do have** a preparation course and tougher accepting criteria.

I would advise, given the time constraints, to stick we the current curriculum and rely on SLU owners to consult with us whenever they feel their units are becoming too heavy. We should explicitly advise them to do so, especially given how much effort is expected in the current format.

I support the issue but I think this is a bit too late for major changes implying a new specialization, that would come *before* Data Wrangling, which is the next one in the curriculum pipeline thanks to @PedroGFonseca, or a new SLU format.

Now, this is a suggestion, I don't want to overwhelm the students any more than you do. If you feel this is wishful thinking from me, call my bullshit (again). :gun:

**Comment by dominguezmaria** [comment]
> To @gaborsomogyi's point, this year we **do have** a preparation course and tougher accepting criteria.
> 
> I would advise, given the time constraints, to stick we the current curriculum and rely on SLU owners to consult with us whenever they feel their units are becoming too heavy. We should explicitly advise them to do so, especially given how much effort is expected in the current format.
> 
> I support the issue but I think this is a bit too late for major changes implying a new specialization, that would come _before_ Data Wrangling, which is the next one in the curriculum pipeline thanks to @PedroGFonseca, or a new SLU format.
> 
> Now, this is a suggestion, I don't want to overwhelm the students any more than you do. If you feel this is wishful thinking from me, call my bullshit (again). 🔫

@jtascensao agree with your concern of there not being time for major format changes.
So let's go with what we have now and accept that there are some SLUs which are a bit heavier than the average.
In these cases, we should accept that:
- the presentation may last for a bit more than 15 minutes
- most of the exercises in the SLU will end up being completed at home, after the bootcamp

Finally, we need to be extra careful with the quality of the Learning Notebooks in these SLUs. They must be reaaaally good!

**Comment by dominguezmaria** [comment]
@jtascensao @PedroGFonseca @gaborsomogyi 

Do we all agree with the following?
- not doing any changes on the specialisation / SLU formats
- keeping the curriculum as it is, even if some SLUs are heavier
- accept that some SLUs will require some extra work at home

If all of us agree (add a 👍 on this comment), I'll close the issue.

**Comment by PedroGFonseca** [comment]
![](https://s-media-cache-ak0.pinimg.com/736x/8a/99/2f/8a992f68f116be06c8ffa9f6ee8e5b00.jpg)
