### ISSUE TITLE
S06 - Model Deployment

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#23]
# S06 - Model Deployment

## Context

Prepare a proposal for the Model Deployment curriculum, to guide discussions.

## Detailed Description

The curriculum must include:

- Outline, containing all BLUs, names, order, and so on
- Main topics covered by each BLU
- A detailed description of the contents of each SLU (to be discussed with the Specialization Lead).

## Possible Implementation

The result should be a document with the curriculum, submitted as a PR.

**Comment by PedroGFonseca** [comment]
Iz good? I can haz close?
