### ISSUE TITLE
Guidelines for notation (SLUs e BLUs)

### ISSUE THREAD

**Issue by hugorcf** [LDSSA/curriculum-development#24]
# Title

Guidelines for notation (SLUs e BLUs)

## Context

There are a lot of machine learning concepts which are used throughout the SLUs and BLUs and whose naming and mathematical notation are not consistent. This impacts learning, especially during the bootcamp if the notation regarding the same concepts keeps changing from SLU to SLU.

## Detailed Description

The idea is to have consistent naming and notation for all the concepts used in more than one SLU/BLU. For instance, if we use $\mathbb{y}$ for the target vector in one SLU and use $y_i$ for its components (pretend that GitHub supports LaTeX...), the same naming ("target vector") and notation should be used in other SLUs and BLUs.

Of course, there might be exceptions (e.g. if in some subfield of machine learning a different notation is more widely used or if there is a clash in notation for a given LU).

## Possible Implementation

1. Create a document with general guidelines for notation (initially based on the notebooks and slides from batch2).
2. Use the guidelines when creating the new notebooks and slides for batch3.
3. Review the notebooks and slides.

**Comment by jtascensao** [comment]
@hugorcf such a document is included in the curriculum. Check it [here](https://github.com/LDSSA/curriculum-development/blob/master/curriculum/01-bootcamp-and-binary-classification.md).

What we need is a kick-ass volunteer! 😁

**Comment by jtascensao** [comment]
I like the notation section of [The Hundred-Page Machine Learning Book]( http://www.goodreads.com/book/show/43190851-the-hundred-page-machine-learning-book).

**Comment by hugorcf** [comment]
That's great @jtascensao! But the document itself does not exist yet, does it?

**Comment by jtascensao** [comment]
No @hugorcf, we need a volunteer to put a proposal forward! In my opinion, it should be one of the first things to do content wise, but that's totally a personal, biased opinion.

Nonetheless, if you have the time to do it (or find someone who does), that would be a tremendous help and I would be really excited about it.

**Comment by dominguezmaria** [comment]
@jtascensao , we have already have the following volunteers:
- @hugorcf preparing guidelines for math expressions and QAing it afterwards in the presentations / LUs
- Ivo Bernardo preparing the presentation template (couldn't find his handle! 😱 )

Are we missing anything?
Best team ever! 😎

**Comment by jtascensao** [comment]
Nop, as effective as always, fearless leader @dominguezmaria.

![](https://media.giphy.com/media/41v9dH9bdhWLe/giphy.gif)

I wasn't aware that @hugorcf was already working on the notation guide, that's quite wonderful.

**Comment by jtascensao** [comment]
Go go @hugorcf :muscle:

**Comment by hugorcf** [comment]
I have a (still short) draft of the mathematical notation guidelines, which I am writing in a Jupyter notebook, to take advantage of its LaTeX support. At this point, I'd like to ask for some feedback, namely:
- on the structure (more focused on notation, and not on definitions);
- what other topics I should include.

I've attached a PDF version of the notebook below:

[ldssa_notation_guidelines.pdf](https://github.com/LDSSA/curriculum-development/files/3220556/ldssa_notation_guidelines.pdf)

**Comment by hershaw** [comment]
I've included a link to this pdf in the contributing guidelines for notebook building. Let me know if a more official version is create and I'll update it.

**Comment by dominguezmaria** [comment]
@hugorcf this is very good :)
I tried thinking if we're missing something, but couldn't come up with an example. So I suggest that:
- the notebook with the guidelines should be placed in this repo
- we add a note in the notebook, saying: "If you're developing an SLU/BLU and find out that there is something missing here, please add it to the notebook and do a pull request with it"
- in the contributing guidelines we add a link to the notebook in this repo, so that we're always pointing to the most updated version of the notation guidelines

I think it's good to go!

**Comment by PedroGFonseca** [comment]
Where did we end up on this? Is it in the wiki? I can haz close?
