### ISSUE TITLE
Risk of excessive similarity with previous batch exercises 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/curriculum-development#26]
Risk of excessive similarity with previous batch exercises 

## Context
Exercises from last year have solutions, and this year's need to be different enough that those don't half-solve them.

## Detailed Description

When making exercises for an SLU, it is quite tempting to take a look at the previous years, and do something "similar, yet different". However,  we must ensure that looking at the previous year solutions is useful, but not too useful, or the students won't need to truly engage with what they have just learned. As we all know, we take the path of least resistance. 

For instance, given that "implement variance by hand" was part of the 2018 batch, this exercise can never be repeated. 

## Possible Implementation

Actions suggested: 
1. Adding to the instructions (for SLU creators) that the exercises should be actively different from the previous year, not just similar with different values. 
2. Telling QAs to be on the lookout for excessive similarity between exercises.

**Comment by dominguezmaria** [comment]
@PedroGFonseca can you take a look at what I wrote [here](https://docs.google.com/document/d/1w6JYwmbw5fWL7NuMSOuxL2LSE7krxesC5uKE8IvfGsE/edit?usp=sharing) in section "How different should the exercises be from last year?". We can iterate on it, so leave any comments!

@gaborsomogyi can you also take a look at what I wrote, and if you agree, have it in mind for the QA?
