### ISSUE TITLE
What to do about "foundational exercises" without repeating last year?

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/curriculum-development#28]
# What to do about "foundational exercises" without repeating last year?

We established that, given that students can easily find last year's exercises, we should not repeat them in the next year. This works fine for most exercises, but some are so foundational that they are difficult to avoid. 

An example of this would be, in the SLU about correlation, having students implement correlation by hand. There isn't much room for manoeuvre (other than asking them to implement it in another language 😅) when trying to avoid repeat content.

Any advice for what to do in these situations?

**Comment by hugorcf** [comment]
In my opinion (having come across those kind of exercises as well while preparing my SLUs), I would say to just leave those as they are. As you said, unless you drop them, it is difficult to change these types of exercises. 

As another example, after teaching the students how to compute things like the mean, standard deviation, etc, using pandas, it is difficult not to have an exercise or two asking them to compute them, even if I use a completely different dataset for this year's batch.

At the end of the day, I don't think that it's a major problem to have a small portion of the exercises being very similar to previous editions, especially the more foundational or "just confirm you know how to do this" exercises.

**Comment by PedroGFonseca** [comment]
Agreed. @jtascensao should we add this to the contributing guidelines?

**Comment by PedroGFonseca** [comment]
Actually the more I work on this the more I see it is a problem. Most of the exercises are foundational (and super basic such as "implement X").

@hershaw @dominguezmaria @jtascensao do we have good reason to believe they can see the previous year's answers? Because if we try to avoid the previous year's foundational exercises then with every academy the Exercise Notebooks will become less relevant 😞

My suggestion is that we adapt them slightly to avoid just "copy paste" solving the question, but that we accept that a student who sees the previous year's answers will have a massive advantage. This may become less of a problem further on (when things get more complex), but at the basics level I feel we'd be losing quality to keep originality

**Comment by dominguezmaria** [comment]
@PedroGFonseca I think that we can keep the foundational ones, as those are really helpful for them to understand the concepts. Ideally we would also add a couple more exercises that would change over the years.

Example:
a) Implement Pearson correlation by hand (this is the same over the years)
b) [Some problem description], compute the correlation between _kgs of butter sold in Iowa_ and _number of divorced couples in New York_ (this one changes)
c) What is the difference between Pearson and Spearman correlation? [multiple answer question] (this one changes, and is always about interpreting the concept)

I think the interpretation ones can always be different enough for us to test if they understood they concept.

I'm not sure if this would be possible in all the cases, though...

**Comment by dominguezmaria** [comment]
@PedroGFonseca can you take a look at what I wrote here in section "How different should the exercises be from last year?". We can iterate on it, so leave any comments!

Once we have something there that we all agree on, we can close this one!

**Comment by CatarinaSilva** [comment]
I was also struggling with this (in fact I lost a couple of hours just seeing if I could find other "foundational exercises") but eventually what I did was:

- I tried to change the context of the problem, the data and the formulation around, so even though the exercise is still recognisable, it makes it a bit harder to find if they want to copy the year before
- I changed when I could the format of inputs/outputs, so even if they copy the code it wouldn't necessarily work out of the box and they would need to do changes

For me the later is the most important in terms of making sure a simple copy/paste does not work. I think this should be enough that copying from the year before has a similar effort to reading the learning notebook and exercises and implementing it properly.

**Comment by dominguezmaria** [comment]
@CatarinaSilva that is a very clear explanation of a very good solution!
In fact, what really matters is that they end up solving the exercise because copying and pasting from last year doesn't work out of the box!

**Comment by PedroGFonseca** [comment]
I believe this one can be closed, thanks all :)
