### ISSUE TITLE
Missing curriculum for S6 - Data Science in the real world

### ISSUE THREAD

**Issue by cimendes** [LDSSA/curriculum-development#37]
# Missing curriculum for S6 - Data Science in the real world

Currently, there are no guidelines for the S6 curriculum. These should be added to the repo containing what is currently being covered in the academy. I'm tagging the people who were responsible for S6 on batch5.

**Comment by UrbanoFonseca** [comment]
I'm drafting a proposal for this specialization's curriculum. Will update and left for discussion when it is ready.
