### ISSUE TITLE
[S06 - BLU14] Add info on how to retrieve data from DB on Heroku

### ISSUE THREAD

**Issue by cimendes** [LDSSA/curriculum-development#38]
# [S06 - BLU14] Add info on how to retrieve data from DB on Heroku

## Context

Currently, we are providing information on BLU on how to reset the Postgres DB in Heroku, but we never cover how to retrieve the information in the database. This is necessary for data drift analysis and/or redeployment. 

## Detailed Description

This is affecting students, particularly during the Capstone project, as a lot of time is spent trying to retrieve the data which is a fairly straightforward thing to do if you know how to. 

##  Possible implementation

A markdown file can be added to BLU14 including instructions on how to retrieve the data. There are two possible ways:
- Using the credentials and a 3rd party program such as DBeaver (such as the one featured in specialization 2)
- Using the dataclip feature in Heroku

**Comment by UrbanoFonseca** [comment]
Agree, seems relevant enough for the Capstone.

We can add another "Extra" guide.

**Comment by UrbanoFonseca** [comment]
Added in https://github.com/LDSSA/curriculum-development/pull/43
