### ISSUE TITLE
[S06 - BLU13] - Test database storage

### ISSUE THREAD

**Issue by cimendes** [LDSSA/curriculum-development#39]
# [S06 - BLU14] - Test database storage

## Context

This is related to [this issue](https://github.com/LDSSA/heroku-model-deploy/issues/19) 

## Detailed Description

A few students have reached the capstone without having set up the database correctly in Heroku and without noticing that no observations were being stored.

Locally, the line in [this issue](https://github.com/LDSSA/heroku-model-deploy/issues/19) works but it doesn't allow Postgres to link to the app.

## Possible Implementation

In BLU13, we are testing the predict/ endpoint. We can follow the same approach by asking to create a "retrieve/" endpoint that responds with the contents of the DB given an ID

**Comment by UrbanoFonseca** [comment]
Added in #43
