### ISSUE TITLE
Add Specialization Leads to CODEOWNERS

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#4]
When Leads are assigned to Specializations, they need to be added to the `CODEOWNERS`.

Additionally, they need to be marked as owners of their Specialization's curriculum.

This way, he will be reviewers of any changes made to their curriculum.

**Comment by PedroGFonseca** [comment]
Not sure about owners of their Specialization's curriculum. 

On that one I'm a bit Jupiterian, and want the Academy to feel "integrated" from end to end. 

The curriculum should be defined by the Academy curriculum owner with the Specialization implementers, but the final word should be the Academy Curriculum owner. (which just happens to be you)

**Comment by jtascensao** [comment]
The guidelines I shared with Chi:
* The Curriculum Team develops a detailed draft of the Specialization's curriculum
* Specialization Leads are assigned to Specializations, in accordance with the curriculum
* The curriculum works like "contract" that is binding for the Lead and the Curriculum Team
* From the assignment onwards, Leads also need to approve contract changes
* The Specialization Lead is free to refine the curriculum (if he so desires) until 6 weeks before the start of the Specialization
* Refinements need to be approved by the Curriculum Team before becoming official.

What do you think, @PedroGFonseca?

I will merge the contributing guidelines now but we can change this later.

**Comment by PedroGFonseca** [comment]
This looks like a good compromise to be both integrated and not micro-managing. 

I like the ` until 6 weeks before the start of the Specialization` part a lot, that will require @dominguezmaria to aggressively pressure them to start early, but would have a really high reward.

**Comment by PedroGFonseca** [comment]
This is now rendered obsolete by the new guidelines, will close
