### ISSUE TITLE
Standard template for Notebooks

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#7]
# Standard template for Notebooks (SLUs and BLUs)

## Context

There is no consistency among notebooks.

This hurts the experience (no sense of integration). 

It impacts learning, as navigation changes from one notebook to another and students need to adapt.

## Detailed Description

This would affect **all notebooks**, from **all SLUs and BLUs**. 

We would need to port all notebooks to the new template.

## Possible Implementation

My suggestion would be to have:

1. Header (markdown table), including Specialization, SLU/BLU and title
2. Title
3. Table of contents
4. Content (and flat is better than nested!)
5. Recap.

**Comment by dominguezmaria** [comment]
Plus one for this one! I'm a consistency fan :)

I suggest adding a to the "Possible implementation" a standard for images and tables, like adding a caption and numerating these.

Also, we should define a standard for the exercises and examples notebooks too.

**Comment by hcastilho** [comment]
It was part of my reasoning when including the `sample` directory in the [instructors](https://github.com/LDSSA/batch3-instructors) repo.

I would suggest changing the sample to a mock BLU with all the rules written directly in the notebook and making the format mandatory (probably renaming it from sample to style guide or something).

Then it could be used as a template for all other material.

**Comment by dominguezmaria** [comment]
Just not to let things die, is anyone currently assigned to the task of defining the notebooks standards?
I can help with this one, if no one has taken it yet.
Not sure under which AOR this falls under!

**Comment by jtascensao** [comment]
@dominguezmaria keep in mind that we are aiming to have only three topics per SLU.

Don't know if this is relevant, but perhaps it is.

**Comment by HugoDLopes** [comment]
I totally agree with this. If the structure is one less thing people need to focus about when opening a notebook -> +1 on this ;)

**Comment by PedroGFonseca** [comment]
Major +1  

How will this be implemented?

**Comment by dominguezmaria** [comment]
I'll draft something next week and show it tou you guys.
Then we improve it based on you suggestions!

(If anyone else is feeling like doing it, just let me know 😄 )

**Comment by PedroGFonseca** [comment]
@dominguezmaria 

![](https://i.imgflip.com/2yjzz0.jpg)

**Comment by dominguezmaria** [comment]
> @dominguezmaria
> 
> ![](https://camo.githubusercontent.com/f630d896587a44420b9decdcdefa68c231a762a4/68747470733a2f2f692e696d67666c69702e636f6d2f32796a7a7a302e6a7067)

@PedroGFonseca I'm finish up some admission test stuff, which has priority over the SLU template (because is due in a couple of weeks 😅 ).
If you have some free time, can you pick this one up?
Otherwise, I'll have time for it next week!
(Sorry for overpromising on this one 😞)

**Comment by PedroGFonseca** [comment]
I can take it!

**Comment by hershaw** [comment]
Let us know when the structure is settled on as we can add it into the CI pipeline and automatically check for them so it will show up like this when you make a PR and are missing something that we can check for:

![image](https://user-images.githubusercontent.com/424192/56099917-4d706000-5f0b-11e9-91be-965589493956.png)

(notice the red next to step that checks the `README.md` exists)

**Comment by jtascensao** [comment]
Reassigned to @PedroGFonseca.

**Comment by dominguezmaria** [comment]
Closing this as @hershaw has already taken care of it! Thanks Sam :)
