### ISSUE TITLE
Limit the number of topics covered per SLU

### ISSUE THREAD

**Issue by jtascensao** [LDSSA/curriculum-development#8]
# Limit the Number of Topics Covered per SLU

## Context

The number of topics covered by SLUs is wildly inconsistent

Also, we try to fit too much in too little time.

## Detailed Description

This would affect all SLUs and function as a guideline for curriculum changes.

According to the [Program Structure](https://github.com/LDSSA/wiki/wiki/Starters-Academy-program-structure-overview,-and-main-concepts), we have 20 minutes of teaching materials per SLU.

Also, we have 15 minutes to present each SLU.

Thus, limited time means we are forced to make trade-offs and keep the essential.

## Possible Implementation

I think we should limit the number of topics covered in each SLU to 5 (4 minutes per topic).

Since presentations last 15 mins, we would have 3 minutes to present each topic.

**Comment by jtascensao** [comment]
Actually, 5 might be too much. A maximum of 3 would be ideal.

**Comment by PedroGFonseca** [comment]
Yep, it would also force us to be very meticulous about our presentations. 

Speaking of which, is there any quality assurance we should be doing on the presentations?

**Comment by gaborsomogyi** [comment]
> Yep, it would also force us to be very meticulous about our presentations.
> Speaking of which, is there any quality assurance we should be doing on the presentations?

We should create some basic rules (use the presentation template, link to it in the readme.md) and enforce its usage to ensure consistency (most SLUs have followed this last time already, but there are some exceptions)
Maybe also work out some guidelines on the structure of the presentation (introduction-overview-explanations-recap)
opened this as a new issue #9

**Comment by HugoDLopes** [comment]
Another topic: will there be any iteration on which SLUs to keep and any new to add?

**Comment by jtascensao** [comment]
@HugoDLopes yes, feel free to open a new discussion if you have ideas!

**Comment by PedroGFonseca** [comment]
One idea is that the presentation is implemented by one person and approved by another (e.g. @gaborsomogyi). 

Part of the issues of the last year was that many presentations were made a bit last second, or were at least only seen for the first time right before the talk.
