### ISSUE TITLE
Standard template for SLU presentations

### ISSUE THREAD

**Issue by gaborsomogyi** [LDSSA/curriculum-development#9]
## Context

SLU presentations are mostly uniform, however, there are some exceptions.
We should make all presentations follow the same guide

## Detailed Description

This would affect presentations from all SLUs, and the accompanying readme.md

## Possible Implementation

Basic rules 
- use the presentation template, from the example SLU
- link to it in the readme.md

Guidelines on the structure of the presentation
- introduction
- overview
- explanations
- recap

**Comment by jtascensao** [comment]
I think we should remove the slide about the instructor.

**Comment by PedroGFonseca** [comment]
Absolutely all for it. Who is owning the implementation on this one?

**Comment by PedroGFonseca** [comment]
@gaborsomogyi how should we proceed? Shall I make a template, for instance?

**Comment by jtascensao** [comment]
@dominguezmaria do we have an owner? :smile:

**Comment by jtascensao** [comment]
Ping

**Comment by dominguezmaria** [comment]
Sorry for being late for the party! Let me find a volunteer for this :)
I'm currently under the water with the test, so if someone is available sooner that would be good, otherwise I can do it later this month.

**Comment by dominguezmaria** [comment]
Closing this after Ivo Bernardo having presented us with this awesome presentation [template](https://docs.google.com/presentation/d/1reOSEfUXVVYlk7-6G5KBNTO8q_www_nsEDjSAYbyjkw/edit#slide=id.p1).
